   version: '3.8'
   services:
     mongodb:
       image: mongo:latest
       container_name: mongodb
       ports:
         - "27018:27017"
       volumes:
         - mongodb_data:/data/db

     app: # Menambahkan service untuk aplikasi
       build: .
       container_name: springboot_app
       ports:
         - "8080:8080"
       depends_on:
         - mongodb

   volumes:
     mongodb_data:
